# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Deploy
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "drp-33-frontend"
          email: "m.kaszlewicz@gmail.com"
          dockerfile_path: ${{env.working-directory}}
          
